const ADMIN = 'ADMIN';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN = 'SING_IN';
const IS_READY = 'IS_READY'
const GET_CLIENT = 'GET_CLIENTS'
const ADD_CLIENT = 'ADD_CLIENTS'
const ADD_QUOTE = 'ADD_QUOTE'
const ADD_PEDIDO = 'ADD_PEDIDO'
const ADD_PRODUCT = 'ADD_PRODUCT'
const ADD_FOTO = 'ADD_FOTO'

export {
    ADMIN,
    SIGN_IN,
    SIGN_OUT,
    IS_READY,
    GET_CLIENT,
    ADD_CLIENT,
    ADD_QUOTE,
    ADD_PEDIDO,
    ADD_PRODUCT,
    ADD_FOTO
}